---
apiVersion: v1
kind: Service
metadata:
  name: mysql-router
  labels:
    app: mysql-router
spec:
  ports:
  - port: 6446
    nodePort: 30446
    protocol: TCP
    name: port6446
  - port: 6447
    nodePort: 30447
    protocol: TCP
    name: port6447
  selector:
    app: mysql-router
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-router
  labels:
    app: mysql-router
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      containers:
      - name: mysqlrouter
        image: mysql/mysql-router:8.0.11
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-user-secret
              key: password
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_HOST
          value: mysql-cluster-0.mysql-cluster
        - name: MYSQL_INNODB_NUM_MEMBERS
          value: "3"
        command:
        - "/bin/bash"
        - "-cx"
        - "exec /run.sh mysqlrouter"
