apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: mysql-local-storage
  local:
    path: /mnt/local/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 10.5.6.8
